name: Auto Update ML IPs

on:
  schedule:
    - cron: '0 3 * * *'  # setiap hari pukul 03:00 UTC (10:00 WIB)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Jalankan Script Resolver
        run: |
          python scripts/resolve-ml.py

      - name: Commit & Push jika ada perubahan
        run: |
          git config user.name "raw-bot"
          git config user.email "raw-bot@example.com"
          git add raw/*.rsc raw/*.txt
          git commit -m "Auto update ML IPs" || echo "No changes"
          git push

